### ISSUE TITLE
ios  Compile DMZ is error?

### ISSUE THREAD

**Issue by hnzlk2014** [card-io/card.io-dmz#10]
ld: warning: ld: warning: ignoring file /Test/dmzTest/opencv_device/lib/libopencv_core.a, missing required architecture x86_64 in file /Test/dmzTest/opencv_device/lib/libopencv_core.a (3 slices)ignoring file /Test/dmzTest/opencv_device/lib/libopencv_imgproc.a, missing required architecture x86_64 in file /Test/dmzTest/opencv_device/lib/libopencv_imgproc.a (3 slices)

Undefined symbols for architecture x86_64:
  "_dmz_deinterleave_uint8_c2", referenced from:
      -[ViewController viewDidLoad] in ViewController.o
ld: symbol(s) not found for architecture x86_64

**Comment by dgoldman-ebay** [comment]
@hnzlk2014 see https://github.com/card-io/card.io-dmz/tree/master/opencv2

Does that help you?

If you are building card.io-dmz as part of [https://github.com/card-io/card.io-iOS-source](https://github.com/card-io/card.io-iOS-source), then there shouldn't be a problem. Are you trying to build card.io-dmz in some other context?

**Comment by hnzlk2014** [comment]
I just want to use DMZ in my project。
1.xcode6 new a project.
2.add dmz and opencv_device to project.
3.
![image](https://cloud.githubusercontent.com/assets/6149516/6910623/229478d0-d788-11e4-9fcd-9079f1bd44c5.png)
4.
![image](https://cloud.githubusercontent.com/assets/6149516/6910691/11025514-d789-11e4-8101-22b17d498f19.png)
5.    IplImage *ySampleImage;
    IplImage *channel1;
    IplImage *channel2;
    dmz_deinterleave_uint8_c2(ySampleImage, &channel1, &channel2);

6.complile
![image](https://cloud.githubusercontent.com/assets/6149516/6910724/7ea2d4ea-d789-11e4-9dbf-bab5ca8d1c57.png)

thank you!

**Comment by dgoldman-ebay** [comment]
@hnzlk2014 for iOS, you'll need to grab the two static libraries from [here](https://github.com/card-io/card.io-iOS-source/tree/master/opencv_device/lib) and add them to your project.

I guess we'll need to bring both the iOS and the Android libraries into this dmz repo. Feel free to start a Pull Request to do so, at least for iOS, once you've worked out the necessary details.

Thanks!

**Comment by hnzlk2014** [comment]
I already did that.
![image](https://cloud.githubusercontent.com/assets/6149516/6932677/8fcbb572-d84f-11e4-9f84-dfe06744a75c.png)

**Comment by dgoldman-ebay** [comment]
@hnzlk2014 I'm just now taking another look at this one...

There are some nested `#define`s that might be causing the problem.

`dmz_deinterleave_uint8_c2()` is only defined if `COMPILE_DMZ` is set.

`COMPILE_DMZ` is set only if both `IOS_DMZ` and `USE_CAMERA` are set.

`IOS_DMZ` is set in `mz.h`, if `TARGET_OS_IPHONE` is set, so you should be good there.

But `USE_CAMERA` is not set within the source files themselves. You will need to set `USE_CAMERA`.

Note that `USE_CAMERA` should be `1` for a device build but `0` for a simulator build. So the best place to set it is in your target's Build Settings, under `Preprocessor Macros`, where you can set it differently for `Any iOS SDK` vs. `Any iOS Simulator SDK`.
