### ISSUE TITLE
Debugging in XCode

### ISSUE THREAD

**Issue by marchinram** [card-io/card.io-dmz#12]
Hey guys, I'm trying to understand how your edge detection code works for detecting the card and whenever I add a break point in dmz_detect_edges in dmz.cpp and start the sample app it never breaks on it.  I put a breakpoint on line 123 of CardIOViewFrame.mm, which is the line which calls dmz_detect_edges and it breaks there.  It just doesn't seem to break in any of the dmz c++ code.  I checked that the optimization level was none for the configuration and not sure what else would cause this.  Do you have any ideas what's going on? Would help me out a lot if I could step through your code.  Any help would be appreciated and thanks for providing the source code, it's been extremely helpful for me!

**Comment by dgoldman-ebay** [comment]
@marchinram you're quite right -- the DMZ code is being optimized, even though the rest of the Debug build is not.

In Xcode, select `icc` in the Project Navigator, then under `TARGETS` select `CardIO`. Go to `Build Phases`. Expand the `Compile Sources` section and scroll down to `dmz_all.cpp`. There you'll see the compiler flag `-O3` and also another compiler flag re vectorization. If you remove those flags, then you should be able to debug into the DMZ code.

You'll also learn why those flags are normally there. Without optimization, card.io will take several seconds to accomplish what it normally does in a fraction of a second. For most tasks this makes the library pretty unusable. But for what you're investigating, it should work well enough, I think.

**Comment by marchinram** [comment]
Thanks!  Yeah I just want to learn what you guys are doing so doesn't need to be optimized.

**Comment by josharian** [comment]
Feel free to also ask detailed and/or code-level questions in issues. You might also find https://www.youtube.com/watch?v=T9TkkZg1L7s helpful for an overview.
