### ISSUE TITLE
How would I train for different font?

### ISSUE THREAD

**Issue by cannyboy** [card-io/card.io-dmz#13]
Presumably the library has been trained to recognise standard credit card fonts...? How could I re-train it to recognise, for instance, car number plates, or printed handwriting?

**Comment by dgoldman-ebay** [comment]
@cannyboy card.io is *very* specialized to scan credit cards. See, for example, [this document](https://github.com/card-io/card.io-dmz/blob/master/docs/expiry_docs/expiry_segmentation.md) to get some idea as to how card.io works.

This library is not extendable to scan car number plates or printed handwriting.
