### ISSUE TITLE
Validation of credit card manually

### ISSUE THREAD

**Issue by Pragati-iOS** [card-io/card.io-dmz#19]
Hello Team,

With reference to the question https://github.com/card-io/card.io-dmz/issues/8 need one confirmation.
I want to create my own screen to fill card information manually and for card validation and formatting I need to copy few files in my project from card-io like dmz-olm.h, CardIONumbersTextFieldDelegate.m, and helper folder. After taking licence do we have to copy complete repo in our project or we can take selective files from project as per our need.

**Comment by josharian** [comment]
You can pick and choose any bits (files, functions, etc) you like.

**Comment by Pragati-iOS** [comment]
Thanks for your reply.There are few more queries mentioned below : 
1. Is there any way that we can stop the debug logs. 
2. After scanning card we see few rects plotted on top of card image for expiry date is there any flag to hide them or should i remove that code.
3. If invalid expiry date is scanned it get visible on manual entry screen Is there a way to hide them.

Thanks,
Pragati

**Comment by dgoldman-ebay** [comment]
> 1. Is there any way that we can stop the debug logs. 

By definition, these occur only in debug builds. But if they are annoying to you, it's easy enough to find and comment out the `NSLog()` lines.

> 2. After scanning card we see few rects plotted on top of card image for expiry date is there any flag to hide them or should i remove that code.

This occurs only in debug builds. But feel free to remove the rect-drawing code if it bothers you.

> 3. If invalid expiry date is scanned it get visible on manual entry screen Is there a way to hide them.

Sorry, not sure what you mean here.
