### ISSUE TITLE
Build Issues with Xcode 7.3.1 and Fabric

### ISSUE THREAD

**Issue by bladebunny** [card-io/card.io-dmz#34]
Hi all, new to Card.IO.  Was hoping to use it for informational cards (e.g. insurance, etc...) where I don't need credit card number capture.  But running into multiple build issues.  Have followed the build setup instructions and installed fabric et al.  I was not able to add the sub-module for DMZ because of a permissions issue so I just downloaded it and added it to the correct folder in the project manually.  When I try to build with Fabric, I keep getting:
 -  local() encountered an error (return code 65)
 - local() encountered an error (return code 69) -- after trying to run as sudo

I also saw a comment in the docs about running "fab concat" after modifying the files -- and tried that -- but the command was not found.

When I try to build via Xcode it fails with:
 - Unknown type 'namespace' in Macros.h  
 - "complex" file not found on the Eigen "Core"

Have searched issues for Card.IO, DMZ and Eigen and can't seem to find any solution.  Wonder if I'm somehow missing some additional build settings on the DMZ/Eigen files.  Maybe got borked because I added them manually?

I have confirmed that my xcbuild path is correct.

Would appreciate any suggestions on how to get this building. I'm pretty much out of ideas at this point.

thanks in advance,
tim

**Comment by bluk** [comment]
Hi, can you reset the dmz submodule back to commit `45e315dd26f8290f653ea19f1cc7111012fe28f2`? Xcode's toolchain has some problems with the latest commits. Will try to fix those as soon as possible.

**Comment by bladebunny** [comment]
I found the thread about updating git config to use the https path for the sub-module and I'm resetting it now to use that.  It seems that it points to the correct commit.  

Just built successfully with Fabric -- checking Xcode now but looks good, thank you!
