### ISSUE TITLE
"МИР"-cards recognition

### ISSUE THREAD

**Issue by goodjohnny** [card-io/card.io-dmz#51]
### Issue description

Hello, Dave!
We are trying to scan an embossed card produced by a Russian payment system "МИР", and it is not recognized by the plugin. The card is always highlighted with a green rectangle, but no data is returned.

Is there any chance you're going to support the "МИР" payment system in the near future?
FYI: the most used "МИР" cards have 16 digits, they are identified by the first three digits (220) and only by them,

If we were to implement "МИР" recognition by ourselves, where should we start? We have found the 'dmz_olm.cpp' file, which contains the settings for the other cards. Are we on the right track?

**Comment by dgoldman-pdx** [comment]
Sorry, @goodjohnny, but I have not been associated with this project for several years now. And it doesn't look like anyone at PayPal is actively updating it anymore. A pity...

[Here's a commit](https://github.com/card-io/card.io-dmz/commit/02e1c4369cae45a3c2c3ed2ccfc81359d1566951) in which a new set of card number prefixes were added for MasterCard (an existing card type). To add a new card type (МИР) you'd need to define a new prefix as in that commit, and also add a new member to the `CardType` enum defined in `dmz_olm.h`, and to the `CardIOCreditCardType` enum defined in `CardIOCreditCardInfo.h`.

**Comment by goodjohnny** [comment]
Thank you, Dave. I'll try.

**Comment by goodjohnny** [comment]
Thanks again. I've done it.

**Comment by dgoldman-pdx** [comment]
👍
