### ISSUE TITLE
How many digits can be recognized with dmz

### ISSUE THREAD

**Issue by Corvuswh** [card-io/card.io-dmz#53]
https://github.com/card-io/card.io-dmz/blob/02e1c4369cae45a3c2c3ed2ccfc81359d1566951/dmz_olm.cpp#L59-L81

In `dmz_olm.cpp` file, the max number of card is `16`. Is there a method to recognise more digits in the card, such as `19`.

**Comment by josharian** [comment]
Not without training a new model. I’m sorry.
